### ISSUE TITLE
How to play video from specific position (set start position)

### ISSUE THREAD

**Issue by GovindaPaliwal** [dailymotion/dailymotion-player-sdk-android#104]
I want to set start position for continue watching ​
​below solution not working. 

```
playerWebView = findViewById(R.id.playerWebview)
       val params = mapOf(
                "video" to "videoXId",
                "start" to "POSITION_IN_SECOND"
        )
        playerWebView.load(loadParams = params);
```

​Is there any other way for this scenario ?

**Comment by michgauz** [comment]
Hi and thanks for your feedback.  ;) 
It seems you're right, let me check with our player team.

**Comment by michgauz** [comment]
Hey !
Actually it should work if you pass `POSITION_IN_SECOND` as an `Int` and not a `String`

**Comment by GovindaPaliwal** [comment]
@michgauz 
Thanks for response.

Now it's worked using Any type of mapOf.
`val map = mutableMapOf<String, Any>()`
