### ISSUE TITLE
How to change color of the bottom progress bar

### ISSUE THREAD

**Issue by sotic** [dailymotion/dailymotion-player-sdk-android#42]
Is it possible to customize the color of the bottom progress bar in the player screen. For instance, we would like to set it as yellow that matches our App UI style better (for now the sdk provides light blue).

**Comment by michgauz** [comment]
Hello @sotic you could use the playerParams to specify additional query parameters when initializing your player.
See https://developer.dailymotion.com/player

```
val playerParams = HashMap<String, String>()
playerParams.put("ui-highlight", "ff0000")
dm_player_web_view.load("x26hv6c", playerParams as Map<String, Any>?)
```
