### ISSUE TITLE
error and reload if internet connection is interrupted 

### ISSUE THREAD

**Issue by MrAndrew7of9** [dailymotion/dailymotion-player-sdk-android#52]
Is there a simple way to load an error and retry button when the video view tries to load on a device which isn't connected to the internet? Currently I'm seeing it load an upside down android head in the top left corner, but no error message with option to retry.

**Comment by martinbonnin** [comment]
Sorry this is not in the SDK at the moment. You'll have to handle that part yourself.

**Comment by MrAndrew7of9** [comment]
Okay, good to know.
