### ISSUE TITLE
Google Cast support

### ISSUE THREAD

**Issue by zar69** [dailymotion/dailymotion-player-sdk-android#58]
Could you please add Google Cast support to the player?

**Comment by zar69** [comment]
What is https://github.com/dailymotion/dailymotion-player-sdk-android/tree/chromecast?
The answer? ;)

**Comment by martinbonnin** [comment]
Adding Google Cast to the player is not easy as typically Google Cast requires a lot of interaction with the app code and is not a simple view like the `PlayerWebView` is today. For an example, one would need to integrate the Cast Icon in the menubar or somewhere else but also add the introductory overlay, minimized controls, etc...

The `chromecast` branch is an experiment for a custom cast receiver but is far from complete.
