### ISSUE TITLE
App is crashing after updating my gradle build to 3.2.1 and applying google gms plugin 

### ISSUE THREAD

**Issue by abderrahmantalbi** [dailymotion/dailymotion-player-sdk-android#63]
when i launch the app i get this error 'com.google.android.gms.ads.identifier.advertisingidclient not found'
i made a search and i found that google has moved all its libraries to gms plugin i think your library needs an update.
thnx

**Comment by martinbonnin** [comment]
Hi! I assume this happens with the sample app in this repo, right ? Does the error happen at runtime or compiletime ?
