### ISSUE TITLE
Min SDK version become 21 ?

### ISSUE THREAD

**Issue by j2sun** [dailymotion/dailymotion-player-sdk-android#75]
I saw in a recent commit:

 buildSrc/src/main/java/Version.kt
@@ -1,5 +1,5 @@
object Version {
    val targetSdkVersion = 28
    **val minSdkVersion = 21**
    val compileSdkVersion = 28
} 

Could you tell me why and will you stop support for android api 17-20 devices?

**Comment by geoffreytan** [comment]
Before api Level 21, the `WebView` was shipped with the OS (see https://developer.chrome.com/multidevice/webview/overview). This `WebView` was updated less often and caused some compatibility issues with the player. 
Starting with api level 21, we can ensure the player has appropriate support from the `WebView`.
