### ISSUE TITLE
Cannot start the media codec on Android TV 9.

### ISSUE THREAD

**Issue by sergiocasero** [dailymotion/dailymotion-player-sdk-android#77]
Hello, we are facing this issue: When we click on a play button from an android tv device with 9.0 versión, the screen is freezed

Device: Xiaomi mi box with Android 9
How to reproduce it: Just play a video

Log:
Cannot start the media codec
    android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2068)
        at org.chromium.media.MediaCodecBridge.c(PG:8)
        at org.chromium.media.MediaCodecBridgeBuilder.createVideoDecoder(PG:68)

Please, this bug is critical, could you solve it?

**Comment by martinbonnin** [comment]
Hi @sergiocasero, this is a bug in the Android WebView. You can follow progress there: https://bugs.chromium.org/p/chromium/issues/detail?id=1051705#c37

**Comment by martinbonnin** [comment]
The new WebView has been released (https://bugs.chromium.org/p/chromium/issues/detail?id=1051705#c69), please check it's working again.
