### ISSUE TITLE
Android 10 - ERR_NO_SUPPORTED_PROXIES

### ISSUE THREAD

**Issue by serabile** [dailymotion/dailymotion-player-sdk-android#86]
Hello, 
I'm just working with ur library and gets this error using android 10 and not reproduced in android 8

DailymotionFragment$onViewCreated: WebView [166493760] received an error with code: -1, description: net::ERR_NO_SUPPORTED_PROXIES from URL:  https://www.dailymotion.com/embed/video/[videoID]

Can u help me ?

**Comment by geoffreytan** [comment]
Hi,

This looks like an error of a proxy configuration. 
Did you check if there is a proxy setting for you connection ? Is it correctly set up?

Best regards,
