### ISSUE TITLE
unable to focus on the controls button of the player like Volume, Setting and Full-Screen control through a  Jio STB remote.

### ISSUE THREAD

**Issue by himanshutct** [dailymotion/dailymotion-player-sdk-android#96]
I have tried to find the view ID OR methods OR param of these controls but nothing is available on Sample project of  Dailymotion link "https://github.com/dailymotion/dailymotion-player-sdk-android/tree/master/sampleapp"

Can you please provide -
- Views ID of  Volume, Setting and Full-Screen buttons. So I can use the request focus thing for focus over controls.
 OR
- Please give any option method so I will hide Volume, Setting and Full-Screen button control always. Like hideVolumebutton() OR view.setVisibility(View.GONE).

Attaching image , where i need focus through remote - [Link for image](https://ibb.co/SNN4Xd6)

**Comment by geoffreytan** [comment]
Hi 👋

This sdk is relying on the Javascript player sdk https://developer.dailymotion.com/player/
Currently the JS player does not provide UI customization so it is currently not possible to do that inside the android sdk.
